#認識姿勢からコンテナのoffset=0を経由して、初期姿勢まで
joint_order:
- joint1
- joint2
- joint3
- joint4
- joint5
- joint6
- joint7
waypoints:
- name: p2
  q:
  - -79.77
  - -13.26
  - 192.63
  - 40.66
  - -155.04
  - 63.7
  - 164.54
# - name: p0 #init
#   q:
#   - -0.0
#   - -4.3
#   - 95.7
#   - 164.6
#   - 263.1
#   - 96.7
#   - 210.0

# - name: p1
#   q:
#   - -83.05
#   - -31.35
#   - 179.98
#   - 111.21
#   - 11.52
#   - 30.0
#   - -4.6
# - name: ninshiki
#   q:
#   - -14.9
#   - -88.1
#   - 150.13
#   - 95.3
#   - 78.9
#   - 30.0
#   - -4.6
# - name: p3
#   q:
#   - 36.69
#   - -48.12
#   - 179.98
#   - 53.91
#   - 102.09
#   - -0.54
#   - -18.31


